services:
  app:
    image: crpi-xy1wtfoe9gyh3dhf.cn-beijing.personal.cr.aliyuncs.com/crlfe/mongo-restore:latest
    platform: linux/amd64
    container_name: mongo-restore
    ports:
      - "3456:3456"
    volumes:
      - backup-uploads:/tmp/backups
      - backup-data:/tmp/backup-data
    environment:
      - PORT=3456
    restart: unless-stopped

volumes:
  backup-uploads:
  backup-data:
